### PR TITLE
fix debug regex

### PR DESCRIPTION
**Pull request by tellnes**
this adds support for jade >= 1.10.0

### CODE REVIEW

**Comment by sidorares** [comment]
thanks @tellnes ! happy to give you repo write / npm publish access if you wish.

**Comment by tellnes** [comment]
I don't mind that. My npm username is `tellnes`. Thanks.

**Comment by sidorares** [comment]
done! Could you bump version and publish?

**Comment by tellnes** [comment]
done

**Comment by sidorares** [comment]
:+1:

**Pull request merged**
